# Generated by Django 3.2.6 on 2025-05-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=100)),
                ('coin_ticker', models.CharField(max_length=4)),
                ('coin_image', models.TextField()),
                ('signature', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
